#!/usr/bin/perl -w
use strict;
for my $script_name (sort glob("bin/*")) {
    my ($short_name) = ($script_name =~ /bin\/(.+)/);
    open my $file, $script_name or die $!;
    <$file>;
    my $docline = <$file>;
    $docline =~ s/^## // or die "$script_name doesn't have a ##-docline.";
    printf "* %10s - %s", $short_name, $docline;
}
